name: tutorialflutterapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.7.3
  audioplayers: ^0.15.1
  vibration: ^1.4.0
  flutter:
    sdk: flutter
  path_provider:

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Musisync
      fonts:
        - asset: fonts/Musisync-KVLZ.ttf
        - asset: fonts/Musisync-qYy6.ttf

  uses-material-design: true

  assets:
    - assets/button-1.mp3
    - assets/sounds/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Mehek_Box_2-lanczos3.png"